# Server
server:
  port: 9800

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:vap}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: false
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


spring:
  redis:
    host: ${REDIS_HOST:192.168.118.213}
    database: ${REDIS_DATABASE:1}
    port:  ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.119.235}:${MYSQL_PORT:3306}/vap_openapi?useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mysql}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    min-idle: 1
    max-wait: 60000
    min-evictable-idle-time-millis: 300000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: select'x'

easyjdbc:
 dialect: mysql
 basePackage: com.vrv.vap.api.dao

logging:
  level:
    com.xphsc: debug
springfox:
  name: 北信源武汉分公司
  title:  开放API等模块
  description:  开放API相关接口文档